### ISSUE TITLE
Support GM4+ Async API

### ISSUE THREAD

**Issue by kupietools** [sizzlemctwizzle/GM_config#92] opened 2018-07-05 01:34 UTC
The settings popup appears to only store the values per domain. How do I get it to store values for my script so I can enter them once and have them be constant wherever the script runs?

**Comment by ssokolow** [comment] 2018-08-04 21:14
Looking at the source code, it appears that GM_config doesn't support the new Greasemonkey 4 APIs so, if you're running it on Greasemonkey 4, the answer is "You can't because, if the Greasemonkey 3 APIs are missing, it falls back to site-specific storage."

**Comment by sizzlemctwizzle** [comment] 2018-08-24 22:31
You can also `@require` the polyfill designed for this problem (supporting the new and old APIs in both GM4 and older version): https://openuserjs.org/libs/sizzle/gm4-polyfill

Just make sure to get the metadata correct. Obviously GM_config should eventually handle this on its own.

**Comment by ssokolow** [comment] 2018-08-25 05:35
I don't have time to properly test things, but, if you don't beat me to it, I'll probably put up a fork that's been retrofitted to use the Greasemonkey 4 APIs within the next month, since ESR 52 is going to go away soon and my script based on GM_config is one of the few things I still have to migrate over.

**Comment by Martii** [comment] 2018-08-26 07:11
@sizzlemctwizzle 

Assume you meant "does not do yet"... TM and VM still support the synchronous API as well.

**Comment by DanMan** [comment] 2018-11-10 17:10
So is anyone working on this? The polyfill doesn't seem to work for me. It keeps using `localStorage`.

**Comment by ssokolow** [comment] 2018-11-10 19:40
Other concerns came up that were more pressing... partly because, at the moment, the only script I've made public which relies on GM_config is specific to a single site where I'm OK with allowing un-privlleged user data to persist.

Of course you can fake a promise. Various libraries (eg. jQuery) provided their own promise implementations before they started to become standardized. 

The problem is that you can't use an asynchronous API (the promises provided by GM4) to fake a synchronous API (the blocking calls provided by GM3 and its clones), which is why the polyfill isn't working for you. GM_config has to be upgraded to use the GM4 APIs before the polyfill can be used to make it work on things which only offer the old APIs.

I do still want to do that, but I have various things of my own which are more urgently in need of an update. (eg. a Linux utility which needs to be updated from GTK+ 2.x to GTK+ 3.x before Kubuntu Linux 14.04 LTS falls out of support in a few months.)

**Comment by sizzlemctwizzle** [comment] 2023-05-07 21:25
PR #111 will finally close this issue once it gets merged.

**Comment by sizzlemctwizzle** [comment] 2023-05-20 16:57
Closed by #111

**Comment by Martii** [comment] 2023-05-21 00:38
@sizzlemctwizzle 
Hmm... Doing some further checking I'm still getting local storage *(confirmed by storage inspector <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> then storage tab)* for OUJS-1 and I use the default `.save` built-in for GMC.

Reopening until resolved.

**Comment by sizzlemctwizzle** [comment] 2023-05-21 19:28
> Hmm... Doing some further checking I'm still getting local storage

Okay, I got it to use the GM APIs with GM/Fx, TM/Fx, and TM/Chrome.

**Closed by sizzlemctwizzle** 2023-05-21 19:28 UTC
Labels: Bugfix, Feedback Needed, Blocking Change

**Comment by Martii** [comment] 2023-05-21 20:13
@sizzlemctwizzle 

Presuming this works in tests can those "global"s identifiers be made into `const` to prevent tampering?

**Comment by sizzlemctwizzle** [comment] 2023-05-21 20:19
> can those "global"s identifiers be made into const to prevent tampering?

I found a cleaner way to do this. See: e0a1d0f

**Comment by Martii** [comment] 2023-05-21 20:35
Retest **PASS** on SM and Fx with e0a1d0f6eacee60ffc95bf7488c619f4c4c7c402 ... You *are* the man!! :) Thank you. Now to go trigger an OUJS-1 update so people get the newest whenever you are finished.

> No idea why it wasn't working for you...

was an issue with .getValue however when I was starting to type it, I noticed you found...

> ... but the new way was much easier to test.

... which is awesome. :smiley_cat: 

> but you kind of just took the wind out of my sails.

Sorry... just the messenger. It took some wind out of me as well but you rose above the occasion as usual. Thank you again.

**Comment by sizzlemctwizzle** [comment] 2023-05-21 20:50
> Retest PASS on SM and Fx

Glad you could confirm my results (and on SM as well).

> whenever you are finished.

I'm finished with this issue now (at least I hope I put this to bed).

> but you rose above the occasion

The first implementation just didn't set right with me. I knew I needed to get `GM` in scope... so I did.

> just the messenger

And I'm glad, because I honestly don't know how long GM_config would have been using local storage without your messages.
