### ISSUE TITLE
Alert Text in Unit Test

### ISSUE THREAD

**Issue by Martii** [sizzlemctwizzle/GM_config#122] opened 2023-05-23 00:08 UTC
Click once... "This value is not saved"
Close
Click again "null"

Fx/GM... tried before the bulk `let` operation too. Not sure if it's GMC or the Unit Test.

---

**EDIT**: Update... checked all the way back with https://github.com/sizzlemctwizzle/GM_config/commit/45573c48d70b45a5d3c8c8a62d08648735484acd before everything was done by myself and sizzle and the `null` is present.

**Comment by sizzlemctwizzle** [comment] 2023-05-23 00:38
> Not sure if it's GMC or the Unit Test.

It's GMC. Verified that this bug didn't exist prior to your bulk ES6 migration. I'm against a bulk migration, so I'm reverting to before your changes.

**Comment by sizzlemctwizzle** [comment] 2023-05-23 00:39
Closing since this isn't an issue with pre-migration GMC.

**Comment by Martii** [comment] 2023-05-23 01:43
Yeah you should have definitely made it clearer. It's not elegant at all mixing between these unfortunately to have the footprint so large which is contrary to the original charter.

If you want a video of the most recent installation a few moments ago I can redo it... but here's a screenshot. i.e. **still not anything related to the ES migration.**


![Still an issue](https://github.com/sizzlemctwizzle/GM_config/assets/114709/69150784-980e-4c7f-be53-4088f11ac82d)

**Comment by Martii** [comment] 2023-05-23 01:57
Here's your video.

https://github.com/sizzlemctwizzle/GM_config/assets/114709/3d94bfe2-7ec4-4fa8-969f-8fca70ba6f50

**Comment by sizzlemctwizzle** [comment] 2023-05-23 03:16
@Martii 
> It's not elegant at all mixing between these unfortunately to have the footprint so large which is contrary to the original charter.

You're right. Keeping it two different ways is a mess. I should have given this more thought regarding the impact on the overall codebase. **I'm reverting my reversion (6ab4d25).**

> I didn't do a direct drop in I examined each logic path. To assume this is also an error.

I figured you did this, but things get a bit wonky in some areas. I should have just trusted that you did your due diligence. Sorry.

> If you don't value my work you won't get it anymore

Not at all. Your work is always top notch. I appreciate all that you do.

> especially since I feel you didn't even try to check this out.

You're right. I just saw you were doing something that I had previously decided shouldn't be done. I never tested it. That's my mistake.

> still not anything related to the ES migration.

> Confirmed also error present in VM and TM via Chromium.

I'm still unable to reproduce what you experience in the image or video and have no idea what is going on, so definitely re-opening this issue.

I am seriously sorry with the way I handled this. I should have been much more open-minded and thoughtful. I'll keep this in mind going forward. Please try to forgive me and continue to contribute.

**Comment by sizzlemctwizzle** [comment] 2023-05-23 18:07
Okay, I was finally able to reproduce. I must have been doing something wrong yesterday. I found that this change to the unit test fixes things:
```js
    'alertTextField': {
        'label': 'Alert Text',
        'type': 'button',
        'click': function() {
            alert(GM_config.get('labelLess'));
            GM_config.set('labelLess', 'Value changed.');
        }
    },
```
I still don't know why this works since it should do the same thing.

**Comment by sizzlemctwizzle** [comment] 2023-05-23 18:24
`get` fails silently when `field.toValue()` returns null.
```js
let field = this.fields[name],
          fieldVal = null;

      if (getLive && field.node) {
        fieldVal = field.toValue();
      }

      return fieldVal != null ? fieldVal : field.value;
```
So this explains the discrepancy. This code needs to be fixed as well, but it isn't the source of the bug.

**Comment by Martii** [comment] 2023-05-23 18:31
When you get a free serene moment please review both PR's. We seems to have come to the same conclusion. ;)

**Comment by Martii** [comment] 2023-05-23 18:41
Re: https://github.com/sizzlemctwizzle/GM_config/issues/122#issuecomment-1559912959

> 
``` js
            alert(GM_config.get('labelLess', true));
            GM_config.set('labelLess', 'Value changed.');
```
... also works here but I will leave it up to you how to change the Unit Test for sure. Your verbiage seems to be resetting something but my verbiage is what has been currently happening even prior to all of our changes in the last few weeks. *(see my oldest commit reference retest [above](https://github.com/sizzlemctwizzle/GM_config/issues/122#issue-1720873574))*

**Closed** 2023-05-23 19:34 UTC
Labels: Feedback Needed
